"""Update column name

Revision ID: 0822cb74198a
Revises: 06f4274bdb36
Create Date: 2024-01-28 22:40:43.618469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0822cb74198a'
down_revision: Union[str, None] = '06f4274bdb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_code', sa.String(length=10), server_default=sa.text("'en'"), nullable=False))
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'language_code')
    # ### end Alembic commands ###
