"""Add is_bot and is_premium columns to user model

Revision ID: 7a9ac51cace9
Revises: 06f4274bdb36
Create Date: 2024-01-30 18:43:07.665027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a9ac51cace9"
down_revision: Union[str, None] = "06f4274bdb36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_bot", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_premium", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_premium")
    op.drop_column("users", "is_bot")
    # ### end Alembic commands ###
